ADR-1194 Add data structures, config and connector for returns submission
hmrc/alcohol-duty-returns pull request #15
Opened 2024-07-23 13:54 UTC by davidfes

2024-07-23 14:11 UTC, davidfes commented on app/uk/gov/hmrc/alcoholdutyreturns/models/returns/AdrReturnsSubmission.scala
> +
Think the singular AdrReturnSubmission sounds better here (+scala file rename)

2024-07-24 09:52 UTC, davidfes commented on app/uk/gov/hmrc/alcoholdutyreturns/models/returns/AdrReturnsSubmission.scala
> +
Done

2024-07-24 10:39 UTC, davidfes commented on test/uk/gov/hmrc/alcoholdutyreturns/repositories/CacheRepositorySpec.scala
> -/*
Test was flaky, plus it's not a unit test if it's accessing Mongo. We have a repo test in 'it' already.

2024-07-24 16:45 UTC, davidfes commented on app/uk/gov/hmrc/alcoholdutyreturns/controllers/ReturnsController.scala
> +          .submitReturn(returnSubmission, ReturnId(appaId, periodKey))
Should validate that if a section is not filled in, the items are not present (Seq/Set being empty)

2024-08-01 16:32 UTC, yasaracar requested changes

2024-08-01 16:32 UTC, yasaracar commented on app/uk/gov/hmrc/alcoholdutyreturns/connector/CalculatorConnector.scala
> +            Try(response.json.as[O]).toOption
As mentioned in team channel, this loses the validation error context. You can use something like:

      Try {
              response.json
                .as[FinancialTransactionDocument]
            } match {
              case Success(doc)       =>
                logger.info(s"Retrieved financial transaction document for appaId $alcoholDutyReference")
                Some(doc)
              case Failure(exception) =>
                logger.warn(
                  s"Parsing failed for financial transaction document with appaId $alcoholDutyReference",
                  exception
                )
                None
            }

2024-08-01 16:32 UTC, yasaracar commented on app/uk/gov/hmrc/alcoholdutyreturns/connector/ReturnsConnector.scala
> +          Try(response.json.as[ReturnCreatedSuccess]).toOption
As mentioned in team channel, this loses the validation error context. You can use something like:

      Try {
              response.json
                .as[FinancialTransactionDocument]
            } match {
              case Success(doc)       =>
                logger.info(s"Retrieved financial transaction document for appaId $alcoholDutyReference")
                Some(doc)
              case Failure(exception) =>
                logger.warn(
                  s"Parsing failed for financial transaction document with appaId $alcoholDutyReference",
                  exception
                )
                None
            }

2024-08-01 17:21 UTC, davidfes commented on app/uk/gov/hmrc/alcoholdutyreturns/controllers/ReturnsController.scala
> +          .submitReturn(returnSubmission, ReturnId(appaId, periodKey))
Validation will happen in a subsequent jira.

2024-08-01 18:58 UTC, yasaracar approved these changes

2024-08-01 19:02 UTC, merged